name: Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: "5.x"
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
    - name: Pack
      run: dotnet pack --no-build /p:Version=1.2.7-pre001 /p:InformationalVersion=1.2.7-pre001-lolformation -o ./releases
    - name: Publish
      run: dotnet nuget push nocommons/build/NoCommons.1.2.7-pre001.nupkg -Source https://www.nuget.org/api/v2/package -ApiKey ${{ secrets.NUGETORGAPIKEY }}

